### 1) Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [4]:
import tensorflow as tf
Vector = tf.constant(2)
print("Dimension of Vector is : ",Vector.ndim)
Scalar = tf.constant([2,3])
print("Dimension of Scalar is : ",Scalar.ndim)
Matrix = tf.constant([[1,2],
                     [3,4]])
print("Dimension of Matrix is : ",Matrix.ndim)
Tensor = tf.constant(tf.zeros(shape=(2,3,5)))
print("Dimension of Tensor is : ",Tensor.ndim)

Dimension of Vector is :  0
Dimension of Scalar is :  1
Dimension of Matrix is :  2
Dimension of Tensor is :  3


### 2) Find the shape, rank and size of the tensors you created in 1

In [5]:
print("Shape of the Tensor is :",Tensor.shape)
print("Rank of the Tensor is :",Tensor.ndim)
print("Size of the Tensor is :",tf.size(Tensor)) 

Shape of the Tensor is : (2, 3, 5)
Rank of the Tensor is : 3
Size of the Tensor is : tf.Tensor(30, shape=(), dtype=int32)


### 3) Create two tensors containing random values between 0 and 1 with shape [5, 300]

In [10]:
tf.random.set_seed(42)
Tensor_1 = tf.constant(tf.random.uniform(shape=[5,300]))
Tensor_2 = tf.constant(tf.random.uniform(shape=[5,300]))
Tensor_1 , Tensor_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

### 4) Multiply the two tensors you created in 3 using matrix multiplication

In [13]:
tf.matmul(Tensor_1,Tensor_2,transpose_b=True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33344 , 73.40498 , 77.15962 , 73.98368 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.085266, 69.06406 , 74.307755, 72.27616 , 76.05668 ],
       [85.056885, 74.266266, 78.00687 , 74.88678 , 83.13418 ]],
      dtype=float32)>

### 5) Multiply the two tensors you created in 3 using dot product

In [17]:
tf.tensordot(Tensor_1,Tensor_2,axes=0)

<tf.Tensor: shape=(5, 300, 5, 300), dtype=float32, numpy=
array([[[[4.57146466e-01, 3.21966261e-01, 6.18703604e-01, ...,
          4.59927619e-01, 2.20503122e-01, 6.12232029e-01],
         [1.81890175e-01, 7.06553087e-02, 4.13265705e-01, ...,
          2.91221023e-01, 2.02211007e-01, 3.42098713e-01],
         [6.11561956e-03, 2.47750491e-01, 5.43439090e-01, ...,
          3.77380133e-01, 3.26972634e-01, 6.57428086e-01],
         [5.88856936e-01, 5.76324835e-02, 8.08152854e-02, ...,
          6.09873176e-01, 4.82111186e-01, 5.50261259e-01],
         [2.43830979e-01, 6.11405969e-01, 6.41095340e-01, ...,
          4.58627582e-01, 4.74320024e-01, 1.71758875e-01]],

        [[3.03364694e-01, 2.13658452e-01, 4.10574824e-01, ...,
          3.05210292e-01, 1.46326989e-01, 4.06280279e-01],
         [1.20703243e-01, 4.68872190e-02, 2.74245232e-01, ...,
          1.93255737e-01, 1.34188250e-01, 2.27018446e-01],
         [4.05835640e-03, 1.64408475e-01, 3.60628933e-01, ...,
          2.50431389e-0

### 6) Create a tensor with random values between 0 and 1 with shape [224, 224, 3]

In [19]:
Tensor_3 = tf.random.uniform(shape=(224,224,3))
Tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
        [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
        [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
        ...,
        [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
        [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
        [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],

       [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
        [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
        [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
        ...,
        [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
        [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
        [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],

       [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
        [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
        [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
        ...,
        [8.4168065e-01, 5.0247252e-01, 2.8834987e-01],
        [3.3173549e-01

### 7) Find the min and max values of the tensor you created in 6

In [21]:
Min_value_of_Tensor_3 = tf.math.reduce_min(Tensor_3).numpy()
Max_value_of_Tensor_3 = tf.math.reduce_max(Tensor_3).numpy()
Min_value_of_Tensor_3 , Max_value_of_Tensor_3

(1.0967255e-05, 0.9999902)

### 8) Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]

In [22]:
Tensor_4 = tf.random.uniform(shape=(1,224,224,3))
squeezed_tensor4 = tf.squeeze(Tensor_4)
squeezed_tensor4.shape

TensorShape([224, 224, 3])

### 9) Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value

In [25]:
Tensor_5 = tf.random.normal(shape=[10])
Tensor_5
tf.argmax(Tensor_5)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

### 10) One-hot encode the tensor you created in 9

In [29]:
Tensor_5_One_Hot = tf.one_hot(tf.cast(Tensor_5,dtype=tf.int32),depth =10)
Tensor_5_One_Hot

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>